import js from "@eslint/js";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  {
    ignores: ["dist/**", "node_modules/**", "*.cjs", "*.js"],
  },
  js.configs.recommended,
  {
    files: ["src/**/*.{js,jsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FormData: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLAnchorElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLLIElement: "readonly",
        HTMLUListElement: "readonly",
        HTMLOListElement: "readonly",
        HTMLTableElement: "readonly",
        HTMLTableRowElement: "readonly",
        HTMLTableCellElement: "readonly",
        HTMLTableSectionElement: "readonly",
        HTMLTableCaptionElement: "readonly",
        HTMLTableColElement: "readonly",
        HTMLHeadElement: "readonly",
        HTMLBodyElement: "readonly",
        HTMLHtmlElement: "readonly",
        HTMLMetaElement: "readonly",
        HTMLLinkElement: "readonly",
        HTMLStyleElement: "readonly",
        HTMLScriptElement: "readonly",
        HTMLTitleElement: "readonly",
        HTMLBaseElement: "readonly",
        HTMLIFrameElement: "readonly",
        HTMLObjectElement: "readonly",
        HTMLEmbedElement: "readonly",
        HTMLParamElement: "readonly",
        HTMLDetailsElement: "readonly",
        HTMLSummaryElement: "readonly",
        HTMLDialogElement: "readonly",
        HTMLDataElement: "readonly",
        HTMLTimeElement: "readonly",
        HTMLProgressElement: "readonly",
        HTMLMeterElement: "readonly",
        HTMLOutputElement: "readonly",
        HTMLTrackElement: "readonly",
        HTMLMapElement: "readonly",
        HTMLAreaElement: "readonly",
        HTMLPictureElement: "readonly",
        HTMLSourceElement: "readonly",
        HTMLTemplateElement: "readonly",
        HTMLSlotElement: "readonly",
        HTMLUnknownElement: "readonly",
        SVGElement: "readonly",
        SVGSVGElement: "readonly",
        SVGPathElement: "readonly",
        SVGCircleElement: "readonly",
        SVGRectElement: "readonly",
        SVGLineElement: "readonly",
        SVGPolylineElement: "readonly",
        SVGPolygonElement: "readonly",
        SVGEllipseElement: "readonly",
        SVGTextElement: "readonly",
        SVGTSpanElement: "readonly",
        SVGTextPathElement: "readonly",
        SVGImageElement: "readonly",
        SVGGElement: "readonly",
        SVGDefsElement: "readonly",
        SVGUseElement: "readonly",
        SVGSymbolElement: "readonly",
        SVGMarkerElement: "readonly",
        SVGPatternElement: "readonly",
        SVGLinearGradientElement: "readonly",
        SVGRadialGradientElement: "readonly",
        SVGStopElement: "readonly",
        SVGClipPathElement: "readonly",
        SVGMaskElement: "readonly",
        SVGFilterElement: "readonly",
        SVGComponentTransferFunctionElement: "readonly",
        SVGAnimateElement: "readonly",
        SVGAnimateTransformElement: "readonly",
        SVGAnimateMotionElement: "readonly",
        SVGMPathElement: "readonly",
        SVGSetElement: "readonly",
        SVGMetadataElement: "readonly",
        SVGDescElement: "readonly",
        SVGTitleElement: "readonly",
        SVGSwitchElement: "readonly",
        SVGForeignObjectElement: "readonly",
      },
    },
    rules: {
      "react/jsx-uses-react": "error",
      "react/jsx-uses-vars": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "no-unused-vars": ["warn", { varsIgnorePattern: "^React$" }],
    },
    settings: {
      react: {
        version: "detect",
      },
    },
  },
];
